### PR TITLE
Various nougat-wip fixes

### PR DESCRIPTION
**Pull request by amillogical**
These changes need more testing from users with the "nougat 4k output issue," but one user (RedCat) has already reported the hpll reset change has fixed the issue for him. I'm hoping that by merging these changes upstream, we can get adequate testing by users who had the nougat output issue, and see if this is ready for replacing the marshmallow kernel.

From the testing that's been done on this branch, I don't believe there are any drawbacks to it compared to the MM kernel.

Regarding the amports reverts, I have [another branch](https://github.com/amillogical/linux-amlogic/commits/nougat-exp) with the focus of a more pure nougat base + 20170515 updates, but it has playback issues on some h264 files still (fixed here with the amports reverts). The long-term goal is to get that branch working well, then merge those updates on top of these.

I updated the commit messages to include better descriptions for each change, but here's a summary of changes in terms of fixes compared to the current nougat-wip branch:
 - 10-8 dithering enabled on 8bit output on <=GXL (fixes the nougat color banding on 10bit media).
 - Reverted output_rgb changes. A user who needed this stated it caused other playback issues for him. On this kernel, it's unnecessary since you can already force rgb output by running `echo 'rgb,8bit' > /sys/class/amhdmitx/amhdmitx0/attr`
 - Some h264 playback issues have been worked around through reverting multi-instance decoding v4 and some depending changes.
 - Fixed 4k h264 playback.
 - Decreased frame skips from tweaking buffers and reverting a cache change that's unnecessary on LE.

### CODE REVIEW

**Comment by amillogical** [comment]
Updated the PR with some minor fixes.
The h265 dynamic_buf_num_margin set to 10 caused some minor picture corruption, but 8 and 16 were fine. Additionally, the vp9 buffer was corrected for the nougat changes after wrxtasy's change.

**Comment by RealJohnGalt** [comment]
This actually isn't quite ready yet, please give me a bit longer.

**Comment by amillogical** [comment]
This actually isn't quite ready yet, please give me a bit longer.

**Comment by amillogical** [comment]
My force push included commits I removed. Closing this PR and reopening.

**Pull request closed without merging**
